#!/bin/bash

set -eo pipefail

esphome_version="1.15.3"

project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd )"

cd "$project_dir"
rm -rf esphome
git clone https://github.com/esphome/esphome --branch "v$esphome_version" --depth 1
cd esphome && rm -rf .git
